### ISSUE TITLE
jobbergate_request confusing return values

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/jobbergate-api#17]
in jobbergate_api_wrapper:
jobbergate_request  PUT/POST operations return a dict if successful, but a string if something goes wrong. This generates errors and stack traces.

**Comment by stephenkeefauver** [comment]
Hi,

Could you add (or send me on slack) the cli command  executed to generate this? I can use that to track down where the traceback is coming from.

Thank you,

Stephen

**Comment by NilesDev** [comment]
Posted in the wrong repo, should have been in jobbergate_cli.
